src/cloud-element-templates/cmd/index.js
src/element-templates/ElementTemplates.js
src/element-templates/cmd/RemoveElementTemplateHandler.js
src/element-templates/cmd/index.js
test/spec/Example.spec.js
test/spec/cloud-element-templates/ElementTemplates.bpmn
test/spec/cloud-element-templates/ElementTemplates.spec.js
test/spec/cloud-element-templates/ElementTemplatesPropertiesProvider.spec.js
test/spec/cloud-element-templates/fixtures/simple.json
test/spec/element-templates/ElementTemplates.bpmn
test/spec/element-templates/ElementTemplates.spec.js
test/spec/element-templates/ElementTemplatesPropertiesProvider.bpmn
test/spec/element-templates/ElementTemplatesPropertiesProvider.spec.js
test/spec/element-templates/fixtures/simple.json

related to https://github.com/camunda/camunda-modeler/issues/3688
Limitations: we are switching planes when we do the operation for a collapsed subprocess. As we replace the element, we also recreate the plane.
While not the best UX, I did not find a satisfactory solution now. Let's keep it like this and revisit should this edge-case be encountered by our users.

fix(elementTemplates): allow removing on root elements 

---

assets/element-templates.css
src/element-templates/components/ElementTemplatesGroup.js
test/TestHelper.js
test/spec/element-templates/ElementTemplatesPropertiesProvider.bpmn
test/spec/element-templates/ElementTemplatesPropertiesProvider.spec.js

closes #11
validator PR: https://github.com/bpmn-io/element-templates-validator/pull/20

feat: visually show deprecated templates

---

CHANGELOG.md
package-lock.json
package.json
src/element-templates/CreateHelper.js
src/element-templates/cmd/ChangeElementTemplateHandler.js
test/spec/element-templates/CreateHelper.spec.js

Before this change we only evaluated the special case for scripts. For everything else we always used the value property. But for some cases e. g. class-based execution listeners we need actually need to set the "class" attribute instead. Also, this align with the json schema definition.
Closes https://github.com/bpmn-io/bpmn-js-element-templates/issues/13
Note: I had to reopen, because I deleted my fork when cleaning up my repos... Forgot about the open pull request. See #15

Support `camunda:executionListener` with `implementationType` property binding

---

CHANGELOG.md
src/cloud-element-templates/ElementTemplatesPropertiesProvider.js
test/spec/cloud-element-templates/ElementTemplatesPropertiesProvider.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3396

fix: display multi-instance configuration in properties panel

---

package-lock.json
package.json
src/cloud-element-templates/CalledElementBehavior.js
src/cloud-element-templates/CreateHelper.js
src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
src/cloud-element-templates/create/CalledElementBindingProvider.js
src/cloud-element-templates/create/TemplateElementFactory.js
src/cloud-element-templates/index.js
src/cloud-element-templates/util/bindingTypes.js
src/cloud-element-templates/util/propertyUtil.js
test/spec/cloud-element-templates/CalledElementBehavior.bpmn
test/spec/cloud-element-templates/CalledElementBehavior.json
test/spec/cloud-element-templates/CalledElementBehavior.spec.js
test/spec/cloud-element-templates/ElementTemplateConditionChecker.spec.js
test/spec/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/cloud-element-templates/cmd/called-element.json
test/spec/cloud-element-templates/create/TemplateElementFactory.spec.js
test/spec/cloud-element-templates/create/TemplatesElementFactory.json
test/spec/cloud-element-templates/fixtures/called-element.json
test/spec/cloud-element-templates/fixtures/condition-called-element.json
test/spec/cloud-element-templates/properties/CustomProperties.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.json
test/spec/cloud-element-templates/properties/CustomProperties.spec.js

This PR implements `zeebe:calledElement` binding. In the implementation, the template developer is required to provide inputs and outputs explicitly as variable propagation is disabled for the templated elements.
Related to https://github.com/camunda/camunda-modeler/issues/3006

feat: support `zeebe:calledElement` templating

---

package.json
rollup.config.mjs
src/cloud-element-templates/linting/index.js
src/cloud-element-templates/util/propertyUtil.js
src/core.js

This exports `core` without calling browser APIs.

fix: correctly export core

---

src/cloud-element-templates/behavior/ConditionalBehavior.js
test/spec/cloud-element-templates/behavior/ConditionalBehavior.spec.js
test/spec/cloud-element-templates/behavior/UpdatePropertiesOrderBehavior.template.json
test/spec/cloud-element-templates/fixtures/chained-conditions.json

closes #49
also fixes https://github.com/camunda/camunda-modeler/issues/4124
Root cause here: https://github.com/camunda/camunda-modeler/issues/4124#issuecomment-1940942140
We will now re-apply conditions and the template until no further changes in conditions are present. This applies all chained conditions.
We need to rename `context.oldTemplate` to avoid naming conflicts with other behaviors that overwrite the context entry. This will cause an infinite loop, as we need the "Before state with conditions" for a proper check.

fix(Conditions): evaluate all chained conditions

---

src/element-templates/properties-panel/ElementTemplatesPropertiesProvider.js
test/spec/element-templates/properties-panel/ElementTemplatesPropertiesProvider.spec.js

Backports https://github.com/bpmn-io/bpmn-js-element-templates/commit/80321e358c6f0fc7620770d69e390eafd7710e8c to C7.
---
Related to https://github.com/camunda/camunda-modeler/issues/4037

feat(platform): always display documentation section

---

src/element-templates/properties-panel/ElementTemplatesPropertiesProvider.js
test/spec/element-templates/properties-panel/ElementTemplatesPropertiesProvider.bpmn
test/spec/element-templates/properties-panel/ElementTemplatesPropertiesProvider.spec.js

Related to / ports https://github.com/bpmn-io/bpmn-js-element-templates/pull/27 to Camunda 7.

feat(platform): always display multi instance configuration

---

CHANGELOG.md
src/cloud-element-templates/Helper.js
src/cloud-element-templates/behavior/ConditionalBehavior.js
src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
src/element-templates/cmd/ChangeElementTemplateHandler.js
test/spec/cloud-element-templates/ElementTemplates.spec.js
test/spec/cloud-element-templates/behavior/ConditionalBehavior.condition-chained-shared-binding.json
test/spec/cloud-element-templates/behavior/ConditionalBehavior.condition-chained.json
test/spec/cloud-element-templates/behavior/ConditionalBehavior.spec.js
test/spec/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/cloud-element-templates/fixtures/condition-chained-shared-binding.json
test/spec/cloud-element-templates/fixtures/condition-chained.json

Verify #78

---

src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
test/spec/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/cloud-element-templates/cmd/task.bpmn

This ensures we don't unnecessarily perform change operations on the diagram. There is more in our code-based and I'd like to discuss if we do this unnecessary work as an oversight or safety feature.
If this is an oversight, then let's only execute what is necessary.

fix(cloud-element-templates): only change type when actually necessary

---

src/cloud-element-templates/behavior/ConditionalBehavior.js

As the suggestions contain a small refactoring, it was hard to do this with suggestions feature in the original PR.
Notable Changes:
Add a convention that when calling `propertiesPanel.zeebe.changeTemplate`, `newTemplate` will always be the original (non-conditional) template. This ensures we only have 1 point where the template is changed, which is in `ensureConditional`. 
This adds an additional `applyConditions` to the operation, but IMO makes the code more readable
Re-ordered listeners to follow the execution path of "I changed a value, how is a condition applied"

chore(conditions): streamline data flow

---

src/cloud-element-templates/behavior/ConditionalBehavior.js
test/spec/cloud-element-templates/ElementTemplates.spec.js
test/spec/cloud-element-templates/behavior/ConditionalBehavior.dependent-dropdowns.json
test/spec/cloud-element-templates/behavior/ConditionalBehavior.spec.js
test/spec/cloud-element-templates/fixtures/condition.bpmn

* With https://github.com/bpmn-io/bpmn-js-element-templates/pull/82 we removed the application of filtered element templates, resolving an infinite loop. 
* We broke a core guarantee (valid values are kept) but did not notice due to missing test coverage
* Restores the pre https://github.com/bpmn-io/bpmn-js-element-templates/pull/82 behavior and adds relevant test coverage
* It ensures that a template is always conditionally applied
* It ensures that condition is only applied once per update cycle, from the _original_ template
* This way we allow the evaluation to stabilize, and stop evaluating recursively (eventually)
---
Related to https://github.com/camunda/camunda-modeler/issues/4249

Ensure existing values are preserved

---

src/cloud-element-templates/properties-panel/ElementTemplatesPropertiesProvider.js
src/cloud-element-templates/properties-panel/properties/custom-properties/index.js
src/components/PropertyDescription.js
src/element-templates/properties-panel/ElementTemplatesPropertiesProvider.js
src/element-templates/properties-panel/properties/CustomProperties.js
test/spec/element-templates/i18n/Translate.bpmn
test/spec/element-templates/i18n/Translate.spec.js
test/spec/element-templates/i18n/Translate.templates.json
test/spec/element-templates/i18n/customTranslate.js

fix missing applying of the `translate` service

---

package-lock.json
package.json
src/cloud-element-templates/properties-panel/properties/custom-properties/FeelProperty.js
src/cloud-element-templates/properties-panel/properties/custom-properties/FeelTextAreaProperty.js
src/cloud-element-templates/properties-panel/properties/custom-properties/StringProperty.js
src/cloud-element-templates/properties-panel/properties/custom-properties/TextAreaProperty.js
src/element-templates/properties-panel/properties/CustomProperties.js
test/spec/cloud-element-templates/fixtures/placeholder.json
test/spec/cloud-element-templates/properties/CustomProperties.placeholder.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.placeholder.json
test/spec/cloud-element-templates/properties/CustomProperties.spec.js
test/spec/element-templates/fixtures/placeholder.json
test/spec/element-templates/properties/CustomProperties.placeholder.bpmn
test/spec/element-templates/properties/CustomProperties.placeholder.json
test/spec/element-templates/properties/CustomProperties.spec.js

Closes #92
Requires https://github.com/camunda/element-templates-json-schema/pull/144 and https://github.com/bpmn-io/properties-panel/pull/363 to be released and integrated.

feat: support placeholders on String and Text properties

---

src/cloud-element-templates/properties-panel/ElementTemplatesPropertiesProvider.js
test/spec/cloud-element-templates/properties-panel/ElementTemplatesPropertiesProvider.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3951

feat: add execution listeners for Zeebe

---

src/cloud-element-templates/util/propertyUtil.js
src/element-templates/properties-panel/properties/CustomProperties.js
test/spec/cloud-element-templates/linting/LinterPlugin.json
test/spec/cloud-element-templates/linting/LinterPlugin.spec.js
test/spec/cloud-element-templates/properties/CustomProperties.feel.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.feel.json
test/spec/cloud-element-templates/properties/CustomProperties.spec.js
test/spec/element-templates/properties/CustomProperties.spec.js

Try out via `npm start`.
Related to https://github.com/camunda/camunda-modeler/issues/4140

feat(cloud): don't apply length and pattern validation to FEEL

---

src/cloud-element-templates/properties-panel/ElementTemplatesPropertiesProvider.js
test/spec/cloud-element-templates/properties-panel/ElementTemplatesPropertiesProvider.entries-visible.bpmn
test/spec/cloud-element-templates/properties-panel/ElementTemplatesPropertiesProvider.spec.js

closes https://github.com/camunda/camunda-modeler/issues/4617
These changes are moving Template group higher on the properties panel list, right below the documentation group

fix: move template group right below documentation group

---

package-lock.json
package.json
test/spec/Example.spec.js
test/spec/cloud-element-templates/fixtures/engines.json

This shows the integration of engines / compatible templates in an E2E setup:
Example works off [these templates](https://github.com/bpmn-io/bpmn-js-element-templates/compare/engines...example-test-bed?expand=1#diff-085b49be6e7d3757d8808464a6c0a126559f06ae64aa3ec5946cf9160e808a23).
Related to #132 

test: verify engines in example test bed

---

assets/element-templates.css

Change text color on incompatible templates button.
`npx @bpmn-io/sr bpmn-io/bpmn-js-element-templates#incompatible-color`
Related to https://github.com/camunda/camunda-modeler/issues/4766

chore: change incompatible button text color to more accessible

---

package-lock.json
package.json
src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
src/cloud-element-templates/create/LinkedResourceProvider.js
src/cloud-element-templates/create/TemplateElementFactory.js
src/cloud-element-templates/util/bindingTypes.js
src/cloud-element-templates/util/propertyUtil.js
test/spec/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/cloud-element-templates/cmd/linked-resource.bpmn
test/spec/cloud-element-templates/cmd/linked-resource.json
test/spec/cloud-element-templates/create/TemplateElementFactory.spec.js
test/spec/cloud-element-templates/create/TemplatesElementFactory.json
test/spec/cloud-element-templates/fixtures/linked-resource.json

This PR adds the ability to template `zeebe:LinkedResource` elements. You can try it out with `npm run start`.
[screencap-2025-01-17-12-02-38.webm](https://github.com/user-attachments/assets/7e48c7de-621a-435c-9454-a2e432bd7448)
closes https://github.com/bpmn-io/bpmn-js-element-templates/issues/137

feat: Support binding type `zeebe:linkedResource`

---

CHANGELOG.md
package-lock.json
package.json
src/cloud-element-templates/Helper.js
src/cloud-element-templates/properties-panel/properties/custom-properties/NumberProperty.js
src/cloud-element-templates/properties-panel/properties/custom-properties/util.js
src/cloud-element-templates/util/FeelUtil.js
test/spec/cloud-element-templates/properties/BooleanProperty.bpmn
test/spec/cloud-element-templates/properties/BooleanProperty.json
test/spec/cloud-element-templates/properties/BooleanProperty.spec.js
test/spec/cloud-element-templates/properties/NumberProperty.bpmn
test/spec/cloud-element-templates/properties/NumberProperty.json
test/spec/cloud-element-templates/properties/NumberProperty.spec.js

deps: update to `@bpmn-io/element-templates-validator@2.3.3`
This PR reverts the breaking changes introduced via [camunda/element-templates-json-schema#156](https://github.com/camunda/element-templates-json-schema/pull/156). Any `feel` value out of the supported enum is allowed, but `static` is used if the property is missing.
Related to https://github.com/camunda/camunda-modeler/issues/4593

fix: make `feel` default to `static` for inputs and outputs

---

src/cloud-element-templates/cmd/ElementTemplateCommands.js
src/cloud-element-templates/cmd/RemoveElementTemplateHandler.js
test/spec/cloud-element-templates/ElementTemplates.bpmn
test/spec/cloud-element-templates/ElementTemplates.spec.js

Closes #114
When removing template from element, documentation and execution listeners (and potentially more non-template properties in the future) are kept.
https://github.com/user-attachments/assets/187c7e81-aac5-4c81-b9c1-6a20e605f512

fix: do not remove documentation and execution listeners when template is removed

---

src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
test/spec/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js

This PR ensures that unrelated properties are not removed when a linked resource gets updated.
Add the following Template to your modeler:
<details>
<pre>
{
"$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
"name": "Broken Task defintion type",
"id": "323540f6-0c23-4f2asd7-b9a1-f821ed92585e",
"appliesTo": [
"bpmn:Task"
],
"elementType": {
"value": "bpmn:ServiceTask"
},
"properties": [
{
"type": "String",
"binding": {
"type": "zeebe:taskDefinition",
"property": "type"
},
"value": "I should never disappear"
},
{
"type": "Dropdown",
"label": "Binding",
"id": "bindingType",
"binding": {
"type": "zeebe:input",
"name": "something"
},
"choices": [
{
"name": "Latest",
"value": "latest"
},
{
"name": "Deployment",
"value": "deployment"
},
{
"name": …

fix(cloud): do not remove unrelated properties on linkedResource update

---

src/cloud-element-templates/properties-panel/properties/custom-properties/index.js
src/element-templates/properties-panel/properties/CustomProperties.js
test/spec/cloud-element-templates/properties/CustomProperties.spec.js
test/spec/element-templates/properties/CustomProperties.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/5039
Change the default for groups to be collapsed by default, can be overwritten by `openByDefault: true` for zeebe element templates (cf. https://github.com/camunda/element-templates-json-schema/pull/177)

Keep groups closed when template is first applied

---

package-lock.json
package.json
src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
src/cloud-element-templates/create/PropertyBindingProvider.js
src/cloud-element-templates/util/bpmnExpressionUtil.js
src/cloud-element-templates/util/propertyUtil.js
test/spec/cloud-element-templates/ElementTemplates.spec.js
test/spec/cloud-element-templates/create/TemplateElementFactory.spec.js
test/spec/cloud-element-templates/fixtures/completion-condition.json
test/spec/cloud-element-templates/properties/BooleanProperty.bpmn
test/spec/cloud-element-templates/properties/BooleanProperty.json
test/spec/cloud-element-templates/properties/BooleanProperty.spec.js
test/spec/cloud-element-templates/properties/CustomProperties.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.bpmn-expression.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.complex-property.json
test/spec/cloud-element-templates/properties/CustomProperties.json
test/spec/cloud-element-templates/properties/CustomProperties.spec.js
test/spec/cloud-element-templates/properties/NumberProperty.bpmn
test/spec/cloud-element-templates/properties/NumberProperty.json
test/spec/cloud-element-templates/properties/NumberProperty.spec.js

When a template defines `completionCondition`, it should be created and updated as a `bpmn:Expression` type. We will use a specialization `bpmn:FormalExpression` as this is the approach taken in https://github.com/bpmn-io/bpmn-js-properties-panel, and also supports automation while the base type can be in natural language.
Related to https://github.com/camunda/tmp-camunda-modeler-adhoc-subprocess/issues/2

Handle `bpmn:Expression` type for BPMN properties.

---

package-lock.json
package.json
src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
test/spec/cloud-element-templates/fixtures/binding-type-property.json
test/spec/cloud-element-templates/properties/CustomProperties.bindingType.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.bindingType.json
test/spec/cloud-element-templates/properties/CustomProperties.bindingType.spec.js
test/spec/cloud-element-templates/properties/CustomProperties.spec.js

* Adds integration tests for element templates using `zeebe:bindingType`. 
* Fixes a bug affecting such templates in combination with call activities. 
* Bumps camunda-bpmn-js-behavior
Related to https://github.com/camunda/camunda-modeler/issues/5027

test: add bindingType integration tests

---

CHANGELOG.md
src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
src/cloud-element-templates/create/AdHocBindingProvider.js
src/cloud-element-templates/create/TemplateElementFactory.js
src/cloud-element-templates/util/bindingTypes.js
src/cloud-element-templates/util/propertyUtil.js
test/spec/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/cloud-element-templates/cmd/ad-hoc.bpmn
test/spec/cloud-element-templates/cmd/ad-hoc.json
test/spec/cloud-element-templates/create/TemplateElementFactory.spec.js
test/spec/cloud-element-templates/create/TemplatesElementFactory.json
test/spec/cloud-element-templates/fixtures/ad-hoc.json
test/spec/cloud-element-templates/properties/CustomProperties.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.json
test/spec/cloud-element-templates/properties/CustomProperties.spec.js

Support zeebe:adHoc with outputCollection and outputElement properties.
Related to https://github.com/camunda/tmp-camunda-modeler-adhoc-subprocess/issues/2 (Issue content is partially outdated)

feat: add `zeebe:adHoc` binding support

---

src/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
src/cloud-element-templates/create/TaskScheduleBindingProvider.js
src/cloud-element-templates/create/TemplateElementFactory.js
src/cloud-element-templates/util/bindingTypes.js
src/cloud-element-templates/util/propertyUtil.js
test/spec/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/cloud-element-templates/cmd/task-schedule.bpmn
test/spec/cloud-element-templates/cmd/task-schedule.json
test/spec/cloud-element-templates/create/TemplateElementFactory.spec.js
test/spec/cloud-element-templates/create/TemplatesElementFactory.json
test/spec/cloud-element-templates/fixtures/task-schedule.json
test/spec/cloud-element-templates/properties/CustomProperties.bpmn
test/spec/cloud-element-templates/properties/CustomProperties.json
test/spec/cloud-element-templates/properties/CustomProperties.spec.js

- Element `zeebe:taskSchedule` can be templated
- Property `zeebe:taskSchedule#dueDate` can be templated
- Property `zeebe:taskSchedule#followUpDate` can be templated
- Both properties are String/Text typed with FEEL support or a Dropdown or Hidden. 
- the `value` set in the template for these properties can only be ISO 8601 date time
- `zeebe:taskSchedule` can only be set if `zeebe:UserTask` is set. 
- `zeebe:taskSchedule` can only exist in a `bpmn:UserTask`
- At least one of the properties needs to be set. 
related to https://github.com/camunda/camunda-modeler/issues/5093

feat: support `zeebe:taskSchedule`

---

src/cloud-element-templates/create/TemplateElementFactory.js
src/utils/ElementUtil.js
test/spec/cloud-element-templates/create/TemplateElementFactory.spec.js

This PR implements automatic expansion of subprocess elements when they are created from element templates, addressing issue https://github.com/camunda/camunda-modeler/issues/5273.
https://github.com/user-attachments/assets/a5f83ff5-f583-470a-8c40-a5b91b5328ed
Closes https://github.com/camunda/camunda-modeler/issues/5273

feat: appended subprocesses should be always expanded
